import React from 'react';
import { FaFileDownload } from 'react-icons/fa';

function Home() {
  return (
    <div class="overflow-hidden">
      <div class="flex justify-evenly pb-4 bg-gradient-to-r from-red-100 to-blue-100">
        <img src="https://www.freeiconspng.com/uploads/emblem-ashoka-chakra-india-shrihub-background-23.png" class="h-20 inline transition ease-in-out delay-150  hover:-translate-y-1 hover:scale-110  duration-300 ...  " ></img>
        <div class="text-3xl font-bold pt-4 transition ease-in-out delay-150  hover:-translate-y-1 hover:scale-110  duration-300 ...  ">ML-Based Captcha Replacement</div>
        <div><p class="text-xl pt-4 transition ease-in-out delay-150  hover:-translate-y-1 hover:scale-110  duration-300 ...  ">Unique Identification Authority of India</p> <p class="text-gray-400">Government of India</p></div>
      </div>
      <div class="flex text-black justify-evenly  bg-gradient-to-r from-sky-100 to-indigo-100 hover:bg-indigo-500 py-4 transition ease-in-out delay-150  hover:-translate-y-1 hover:scale-110  duration-300 ...  ">
        {/* <div class="relative group">
          <div class="invisible group-hover:visible absolute">
            This div becomes visible on hover!
          </div>
          Hover over me
        </div> */}

       
       <div class="relative group"> 
          BEHAVIORAL ANALYSIS VERIFICATION
            <div class="invisible group-hover:visible absolute group-hover:relative h-96 w-96 pt-20 px-10 group-hover:border-2 group-hover:border-gray-900 group-hover:bg-gradient-to-r from-red-100 to-blue-100">
            <p class="transition ease-in-out delay-150  hover:-translate-y-1 hover:scale-110  duration-300 ...  ">Track and analyze mouse movements, scroll patterns, and clicks. Human mouse movements are generally less smooth and more random compared to bots.</p>
            <p class="transition ease-in-out delay-150  hover:-translate-y-1 hover:scale-110  duration-300 ...  ">Capture and analyze typing patterns, including typing speed, intervals between key presses, and the overall rhythm.</p>
            <p class="transition ease-in-out delay-150  hover:-translate-y-1 hover:scale-110  duration-300 ...  ">For mobile users, analyze touch patterns, including pressure, duration, and finger positioning.</p>
          </div>
         
       </div>
         
        <p class="relative group">VISUAL INTERACTION 
          <div class="invisible group-hover:visible absolute group-hover:relative h-96 w-96 pt-20 px-10 group-hover:border-2 group-hover:border-gray-900 group-hover:bg-gradient-to-r from-red-100 to-blue-100">
            <p class="transition ease-in-out delay-150  hover:-translate-y-1 hover:scale-110  duration-300 ...  ">Present users with interactive tasks, such as dragging objects to a specific location (e.g., drag-and-drop puzzles). These tasks can be challenging for bots but intuitive for humans.</p>
          </div>
        </p>
        <p class="relative group"> AUDIO CAPTCHAS 
            <div class="invisible group-hover:visible absolute group-hover:relative h-96 w-96 pt-20 px-10 group-hover:border-2 group-hover:border-gray-900 group-hover:bg-gradient-to-r from-red-100 to-blue-100">
             <p class="transition ease-in-out delay-150  hover:-translate-y-1 hover:scale-110  duration-300 ...  ">Ask users to respond to simple audio challenges, like repeating a word or a series of numbers. Speech recognition models can analyze the response to determine if it was generated by a human or a bot.</p>
          </div>
        </p>
        <p class="relative group">TEXT CHALLENGES  
          <div class="invisible group-hover:visible absolute group-hover:relative h-96 w-96 pt-20 px-10 group-hover:border-2 group-hover:border-gray-900 group-hover:bg-gradient-to-r from-red-100 to-blue-100">
          <p class="transition ease-in-out delay-150  hover:-translate-y-1 hover:scale-110  duration-300 ...  ">Instead of asking users to solve CAPTCHAs, ask them to complete a simple sentence or solve a word puzzle. The complexity of natural language understanding makes it difficult for bots to generate appropriate responses.</p>
        </div>
        </p>
        <p class="relative group">BIOMETRICS
          <div class="invisible group-hover:visible absolute group-hover:relative h-96 w-96 pt-20 px-10 group-hover:border-2 group-hover:border-gray-900 group-hover:bg-gradient-to-r from-red-100 to-blue-100">
        <p class="transition ease-in-out delay-150  hover:-translate-y-1 hover:scale-110  duration-300 ...  ">Use facial recognition, fingerprint scanning, or voice recognition as a more secure alternative to traditional CAPTCHAs.</p>
        </div>
        </p>
      </div>

      
      

      
      <div class="h">

      </div>
      <div class=" pt-10 border border-2 px-12 bg-gradient-to-r from-red-100 to-blue-100">
      <div class=" w-full  mx-auto h-96 ">
          <div class="overflow-hidden rounded-lg ">
              <div class=" flex animate-loop-scroll  ">
                
                  <img class="w-full h-96 flex-shrink-0 transition-transform duration-500 transition ease-in-out delay-150 bg-blue-900 hover:-translate-y-1 hover:scale-110 hover:bg-indigo-500 duration-300 ... max-w-none relative" src="https://media.istockphoto.com/id/1144287308/photo/happy-diverse-friends-group-sharing-social-media-news-holding-phones.jpg?s=170667a&w=0&k=20&c=oPQz8vUrc1wz1S7_aE57jF554kh1cuJFqE2-U68uY2o="></img>
                <p class=" absolute text-4xl text-white font-bold right-20 bottom-2990 ">We want you to get<p></p> rid of cyber crimes and be happy</p>
                 <img class="w-full flex-shrink-0 transition-transform duration-500 transition ease-in-out delay-150 bg-blue-900 hover:-translate-y-1 hover:scale-110 hover:bg-indigo-500 duration-300 ... max-w-none h-96 " src="https://cdn.mos.cms.futurecdn.net/XUbwwdwsSwraHRrgVnRAgC-650-80.jpg" alt="Image 2" ></img>
                <p class="absolute text-4xl text-white font-bold right-0 bottom-0">For that we have designed a new human recognition sysytem<p></p> in which you need to draw the captcha</p>
                
                <img class="w-full flex-shrink-0 transition-transform duration-500 transition ease-in-out delay-150 bg-blue-900 hover:-translate-y-1 hover:scale-110 hover:bg-indigo-500 duration-300 ... max-w-none h-96" src="https://i0.wp.com/human-id.org/wp-content/uploads/2021/11/blog36.2.png?resize=512%2C267" alt="Image 3" ></img>
                <img class="w-full h-96 flex-shrink-0 transition-transform duration-500 transition ease-in-out delay-150 bg-blue-900 hover:-translate-y-1 hover:scale-110 hover:bg-indigo-500 duration-300 ... max-w-none relative" src="https://media.istockphoto.com/id/1144287308/photo/happy-diverse-friends-group-sharing-social-media-news-holding-phones.jpg?s=170667a&w=0&k=20&c=oPQz8vUrc1wz1S7_aE57jF554kh1cuJFqE2-U68uY2o="></img>
                <p class=" absolute text-4xl text-white font-bold right-20 bottom-2990 ">We want you to get<p></p> rid of cyber crimes and be happy</p>
              </div>
          </div>
      </div>
      
     
     
        
        <div class="h-96 text-gray-700 text-7xl font-bold pt-10 transition ease-in-out delay-150  hover:-translate-y-1 hover:scale-110  duration-300 ...  pl-20">What are we <p></p>going to do !!</div>
        <div class="pb-20 text-gray-700 text-5xl">Download our Reserach Paper  <FaFileDownload class="mt-4 mb-20 transition ease-in-out delay-150  hover:-translate-y-1 hover:scale-110  duration-300 ...  "/>
        <p class="transition ease-in-out delay-150  hover:-translate-y-1 hover:scale-110  duration-300 ...  text-right -pr-10">Our motive is to make you
          <p></p>people free of cyber crimes</p><p class="pt-10 text-4xl transition ease-in-out delay-150  hover:-translate-y-1 hover:scale-110  duration-300 ... w-1/2 ">We will be introducing a new feature which will distinguish bots from humans better than captcha</p>
        <p class="pt-20 text-3xl transition ease-in-out delay-150  hover:-translate-y-1 hover:scale-110  duration-300 ...  -pr-10 text-right">It will be a captcha but of different type </p>
        <p class="text-2xl pt-10 transition ease-in-out delay-150  hover:-translate-y-1 hover:scale-110  duration-300 ... w-1/2 ">We will let the user only read and write captcha because it is now very simple for I and bots to read and write captcha. In place of that we will be providing a aome characters and will ask the user to draw that character on digital whiteboard. If the user draw it perfectly than the user is a bot or AI because no human can draw it perfectly.</p>
        <p class="text-2xl pt-10 transition ease-in-out delay-150  hover:-translate-y-1 hover:scale-110  duration-300 ...  text-center">That the new feature which will be provided from us to the new Tech World. Thank You!!</p></div>
       
      </div>

      <div class="bg-gradient-to-r from-red-100 to-blue-100 pb-10 ">
      <div class="text-center text-4xl text-black animate-bounce pt-20 pb-10 font-underlined">Some of the famous tweets on BOTS vs HUMANS</div>
      <div class="flex flex-col items-center">
      <img src="https://krebsonsecurity.com/wp-content/uploads/2017/08/jcox-580x515.png" class=" animate-pulse h-96 w-2/5 pt-20 transition ease-in-out delay-150  hover:-translate-y-1 hover:scale-110  duration-300 ...  ">
      </img>
        <img src="https://krebsonsecurity.com/wp-content/uploads/2017/08/tweetbotattack-580x284.png" class=" animate-pulse  h-96 w-2/5 pt-20 transition ease-in-out delay-150  hover:-translate-y-1 hover:scale-110  duration-300 ...  "></img>
           <img src="https://media.nbcnewyork.com/2020/07/3083610747-1080pnbcstations.jpg?quality=85&strip=all&resize=1200%2C675" class=" animate-pulse  h-96 w-2/5 pt-20 transition ease-in-out delay-150  hover:-translate-y-1 hover:scale-110  duration-300 ...  "></img>
        </div>
        </div>
      
      <div class="text-black bg-gradient-to-r from-sky-100 to-indigo-100 text-xl text-center">ML Based Captcha Replacement © 2024</div>
    </div>
  );
}

export default Home;